### ISSUE TITLE
Week 9 Project Review

### ISSUE THREAD

**Issue by AlreadyAsleep** [kpilbean/JPs_Porcelain_Punishers#1]
Hey Kate! Read through your design doc and everything you describe sounds good and looks like it will meet the requirements. I would recommend trying to get some of it coded as soon as possible so I can give you better feedback on your work

**Comment by kpilbean** [comment]
Ben, Have gotten a bunch done and pretty happy so far with progress.  Couple glitches of things that aren't displaying the way I want yet, but wanted you to know I've gotten some actual code in there finally.  ;)
