### ISSUE TITLE
Week 11 Project Review

### ISSUE THREAD

**Issue by AlreadyAsleep** [kpilbean/JPs_Porcelain_Punishers#2]
Below is a review of your project that will outline how it stacks up against the requirements and what opportunities I see.
Here is a link to the requirements for reference: https://docs.google.com/document/d/1OHe_R4irOpoKX3QGD3HZWCgNLaHScVuviWGa95Be830/edit#
## Mandatory Requirements
- Responsive Design: Site doesn't respond fully. I would add a media query and render a hamburger menu on mobile
- Javascript: Saw the file but it wasn't linked to the html properly. Add ```<script src="java.js"></script>``` to the bottom of your body. Also rename this file to index.js pls
- Comments: some but I need more on the js and html files
- 5 commits: 12 so good
- README: ✔️ 
## Feature Requirements
Based on our conversations and what I can see in your site I would attempt the following features from the requirements list:
- Hamburger menu
- Felxbox ✔️ 
- Image Carousal ✔️ 

Get your js file linked properly and clear up the other things I mentioned and you'll be in good shape 😄

**Comment by kpilbean** [comment]
Ok, I'm 99% sure I covered everything you mentioned.  Some things still driving me batty, but with these concussion symptoms, not able to pretty it up as I would like it to be.  If you get a chance in the morning to check it out again, that would be awesome, but definitely don't sweat it if not.  Really appreciate all your help and support throughout the semester!  And best of luck with your family - will keep you all in my thoughts and prayers for everything to turn out safe, healthy, and happy.  :)
